### ISSUE TITLE
Prepare for Terraform 0.12

### ISSUE THREAD

**Issue by meyskens** [src-d/terraform-provisioner-online-rescue#3]
We should prepare this for Terraform 0.12.
This consists of
* Migrating to Go modules
* Vendoring in TF 0.12 and run tests

**Comment by rporres** [comment]
PR: https://github.com/src-d/terraform-provisioner-online-rescue/issues/3

**Comment by driosalido** [comment]
> PR: #3

The never ending link...

**Comment by rporres** [comment]
PR: #4 😂

**Comment by meyskens** [comment]
https://github.com/src-d/terraform-provisioner-online-rescue/releases/tag/v0.2.0 
Merged and released!
